########################################################################################
#|------------------------------------------------------------------------------------|#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|               |#
#|               |#
#|               |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|      Youtube:      www.youtube.com/@davigamer1614                                  |#
#|      Github:       https://github.com/BEAMONDO/                     |#
#|                                                                                    |#
#|                                                                                    |#
#|                                                                                    |#
#|------------------------------------------------------------------------------------|#
########################################################################################

Config:
    mensaje-heal: true
    permiso-texto:
    - '&aHas sido curado'
    no-permiso-texto:
    - '&cNo tienes permiso para ejecutar ese comando'

    
    