# ################################################################################## #
# +--------------------------------------------------------------------------------+ #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |                __          __        ___            ___  __                    | #
# |               /__` | |\/| |__) |    |_        |__| |_   |__| |                 | #
# |               .__/ | |  | |    |___ |___      |  | |___ |  | |___              | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |      Youtube:    www.youtube.com/@davigamer1614                                | #
# |      Github:     https://github.com/BEAMONDO/Minecraft-Plugin-SimpleHeal       | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# +--------------------------------------------------------------------------------+ #
# ################################################################################## #


#   help-message: enable or disable the command message "/sh help"
#   reload-message: enable or disable the command message "/sh reload"
#   version-message: enable or disable the command message "/sh version"
#   heal-message: enable or disable the command message "/heal" and "/heal <player>"
#   pay-to-heal: enable or disable the option to pay to heal (if enable is necessary the plugin Vault)
#   heal-price: amount to pay if use "/heal" command if (pay-to-heal) is enable
#   no-argument-message: enable or disable the command message "/sh" if it not have any argument
#   no-perm-message: enable or disable message when use a command and don`t have permission


Config:
  help-message: true
  reload-message: true
  version-message: true
  heal-message: true
  pay-to-heal: false
  heal-price: 1000
  no-argument-message: true
  no-perm-message: true