main: davigamer161.simpleheal.SimpleHeal
version: 1.1.1
name: SimpleHeal

commands:
  heal:
    description: Comando para curar
  simpleheal:
    description: Comando principal
    aliases: [sh]
permissions:
  simpleheal.heal:
    description: Sirve para curar

  simpleheal.reload:
    description: Sirve para recargar el plugin
  simpleheal.help:
    description: Sirve para ver lista de comandos
  simpleheal.version:
    description: Sirve para ver la version del plugin