main: davigamer161.simpleheal.SimpleHeal
version: 1.4.2
name: SimpleHeal
softdepend: [Vault]

commands:
  simpleheal.*:
    default: op
    description: Todos los permisos
  heal:
    description: Comando para curar
  simpleheal:
    description: Comando principal
    aliases: [sh]
permissions:
  simpleheal.heal:
    description: Sirve para curar
  simpleheal.heal.others:
    description: Sirve para curar a otros
  simpleheal.reload:
    description: Sirve para recargar el plugin
  simpleheal.help:
    description: Sirve para ver lista de comandos
  simpleheal.version:
    description: Sirve para ver la version del plugin
  simpleheal.econ.exempt:
    description: Sirve para no pagar al usar /heal
  simpleheal.econ.exempt.others:
    description: Sirve para no pagar al usar /heal para otros