# ################################################################################## #
# +--------------------------------------------------------------------------------+ #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |                __          __        ___            ___  __                    | #
# |               /__` | |\/| |__) |    |_        |__| |_   |__| |                 | #
# |               .__/ | |  | |    |___ |___      |  | |___ |  | |___              | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |      Youtube:    www.youtube.com/@davigamer1614                                | #
# |      Github:     https://github.com/BEAMONDO/Minecraft-Plugin-SimpleHeal       | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# +--------------------------------------------------------------------------------+ #
# ################################################################################## #


#   update-message: activar o desactivar el mensaje de actualizacion disponible al entrar al servidor
#   no-argument-message: activar o desactivar el mensaje del comando "/sh" en el caso de no tener ningun argumento
#   no-perm-message: activar o desactivar el mensaje para cuando usas un comando y no tienes permiso

#   heal-message: activar o desactivar el mensaje del comando "/heal"
#   pay-to-heal: activar o desactivar la opcion de pagar para curar (si se activa es necesario el plugin Vault y EssentialsX)
#   pay-to-heal-price: cantidad a pagar al usar "/heal" si la opcion (pay-to-heal) esta activa

#   wait-to-heal: activar o desactiva la opcion de esperar para curar
#   wait-to-heal-time: cantidad de tiempo (en segundos) que debes esperar para usar el comando "/heal"


Config:
  update-message: true
  no-argument-message: true
  no-perm-message: true
  heal-message: true
  pay-to-heal: false
  pay-to-heal-price: 1000
  wait-to-heal: true
  wait-to-heal-time: 300